# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: lucaslopes2
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: helpinho
service: helpinho

provider:
  name: aws
  runtime: nodejs20.x
  architecture: arm64
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  memorySize: 128
  logRetentionInDays: 1
  timeout: 15

package:
  individually: true

functions:
   api:
    handler: dist/src/lambda.handler
    events:
      - httpApi:
          method: any
          path: /{proxy+}

plugins:
  - serverless-jetpack
  - serverless-offline